language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.8.x on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      before_install:
        - python3.8 -m pip install --upgrade pip pipenv setuptools
install: pipenv install --dev  # all three OSes agree about 'pip3'
script: pytest
